name: PyPi Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.0.0
    - name: Poetry build
      run: poetry build
    - name: Publish to Test PyPi
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry publish -r testpypi -u "__token__" -p ${{ secrets.test_pypi_password }}
    - name: Publish to Pypi
      run: poetry publish -u "__token__" -p ${{ secrets.pypi_password }}
      
